# Generated by Django 3.0.3 on 2020-09-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='sortie',
            field=models.DateTimeField(null=True),
        ),
    ]
