# Generated by Django 3.0.3 on 2020-09-09 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_auto_20200908_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='Personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointage.Personne', verbose_name='passage'),
        ),
    ]
