# Generated by Django 3.0.3 on 2020-09-10 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pointage', '0004_auto_20200910_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entree',
            old_name='Personne',
            new_name='User',
        ),
        migrations.CreateModel(
            name='PrevEntree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree', models.DateTimeField()),
                ('sortie', models.DateTimeField(null=True)),
                ('Personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='prevpassage')),
            ],
        ),
    ]
