# Generated by Django 3.0.3 on 2020-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0005_auto_20200910_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventree',
            old_name='Personne',
            new_name='User',
        ),
    ]
