# Generated by Django 3.0.3 on 2020-09-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0006_auto_20200911_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='entree',
            name='salle',
            field=models.CharField(choices=[('A', 'Atelier'), ('B', "Bureau d'étude"), ('D', 'Découpe laser')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='preventree',
            name='salle',
            field=models.CharField(choices=[('A', 'Atelier'), ('B', "Bureau d'étude"), ('D', 'Découpe laser')], default='B', max_length=1),
        ),
    ]
