# Generated by Django 3.0.3 on 2020-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0008_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asso',
            name='value',
            field=models.CharField(choices=[('warning', 'VED'), ('info', 'HV'), ('success', 'DV3D')], default='warning', max_length=8),
        ),
    ]
