# Generated by Django 3.0.3 on 2020-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0009_auto_20200914_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asso',
            name='value',
        ),
        migrations.AddField(
            model_name='asso',
            name='color',
            field=models.CharField(choices=[('warning', 'warning'), ('info', 'info'), ('success', 'success')], default='warning', max_length=8),
        ),
    ]
