# Generated by Django 3.0.3 on 2020-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0010_auto_20200914_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asso',
            name='color',
            field=models.CharField(choices=[('danger', 'danger'), ('info', 'info'), ('success', 'success')], default='danger', max_length=8),
        ),
    ]
